# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedata',
            name='source',
            field=models.CharField(max_length=128),
        ),
    ]
