# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20180322_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('source', models.SmallIntegerField(choices=[(0, 'poloniex'), (1, 'bittrex'), (2, 'binance'), (3, 'bitfinex'), (4, 'kucoin'), (5, 'gdax'), (6, 'hitbtc')])),
                ('transaction_currency', models.CharField(max_length=8)),
                ('counter_currency', models.SmallIntegerField(choices=[(0, 'BTC'), (1, 'ETH'), (2, 'USDT'), (3, 'XMR')])),
                ('base_volume', models.FloatField(null=True)),
                ('open_price', models.BigIntegerField(null=True)),
                ('high_price', models.BigIntegerField(null=True)),
                ('low_price', models.BigIntegerField(null=True)),
                ('close_price', models.BigIntegerField(null=True)),
                ('extra', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
