# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_historyprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('market_price_usd', models.FloatField(null=True)),
                ('hash_rate', models.FloatField(null=True)),
                ('total_fees_btc', models.BigIntegerField(null=True)),
                ('n_btc_mined', models.BigIntegerField(null=True)),
                ('n_tx', models.IntegerField(null=True)),
                ('n_blocks_mined', models.IntegerField(null=True)),
                ('minutes_between_blocks', models.FloatField(null=True)),
                ('totalbc', models.BigIntegerField(null=True)),
                ('n_blocks_total', models.IntegerField(null=True)),
                ('estimated_transaction_volume_usd', models.FloatField(null=True)),
                ('blocks_size', models.BigIntegerField(null=True)),
                ('miners_revenue_usd', models.FloatField(null=True)),
                ('nextretarget', models.IntegerField(null=True)),
                ('difficulty', models.BigIntegerField(null=True)),
                ('estimated_btc_sent', models.BigIntegerField(null=True)),
                ('miners_revenue_btc', models.IntegerField(null=True)),
                ('total_btc_sent', models.BigIntegerField(null=True)),
                ('trade_volume_btc', models.FloatField(null=True)),
                ('trade_volume_usd', models.FloatField(null=True)),
            ],
        ),
    ]
